id: A843F79B6
title: Dedication (Sangye tenpa...)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:23:36.120099
  last_modified_at: 2022-03-01 03:23:36.120106
