id: A843F79B6
title: Temple Dedication Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:23:36.127326
  last_modified_at: 2022-03-01 03:23:36.127331
